server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ghigoviu/spring-ms-tuto
          search-paths: config-data
  application:
    name: config-service
